#!/bin/bash

# Welcome to the Nimble laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -e

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

pre_setup() {
  if [ ! -f "$HOME/.Brewfile" ]; then
    touch "$HOME/.Brewfile"
  fi
}

install_ruby() {
  fancy_echo "Installing Ruby"
  
  gem update --system
}

append_general_dependencies() {
  fancy_echo "Appending general dependencies to Brewfile"

  tee "$HOME/.Brewfile" <<-EOF
    # mas-cli to install macOS apps
    brew "mas"
EOF
}

append_ios_dependencies() {
  fancy_echo "Appending iOS's dependencies to Brewfile"

  tee -a "$HOME/.Brewfile" <<-EOF
    mas "XCode", id: 497799835
EOF
}

ask_for_repo() {
  read -r -p "What is the Github repo you want to connect to? (team/repo)" repo
  
  fancy_echo "Please follow the instruction on the web page."
  open "https://github.com/$repo/settings/actions/runners/new"
}

run_github_actions() {
  ask_for_repo
}

install() {
  pre_setup

  append_general_dependencies

  append_ios_dependencies

  install_ruby

  brew cleanup

  run_github_actions
}

# Run
install

fancy_echo "Installation successful"
